inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/StringLiterals:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false